In [1]:
import numpy as np
from string import ascii_uppercase
from load import get_data
from sortedcontainers import SortedList

In [2]:
file_ex, file_data = get_data('day5')

In [3]:
ex = file_ex.read().split("\n")
data = file_data.read().split("\n")

In [4]:
ex

['    [D]    ',
 '[N] [C]    ',
 '[Z] [M] [P]',
 ' 1   2   3 ',
 '',
 'move 1 from 2 to 1',
 'move 3 from 1 to 3',
 'move 2 from 2 to 1',
 'move 1 from 1 to 2']

In [258]:
matriz_letter = []
boxes_raw = []
moves = []

crate2num = dict(zip(ascii_uppercase, range(1,27)))

for irow in range(len(ex)):
    if ' 1' in ex[irow]:
        for i in ex[irow+2:]:
            moves.append(np.asarray(i.replace("move ", "").replace(" from ", " ").replace(" to ", " ").split(),dtype=int))
        break
    else:
        boxes_raw.append(ex[irow])

for i in SortedList(boxes_raw):
    matriz_letter.append(i.replace("]", ",").replace("[", ",").replace(", ,", ",")[1:-1].replace('   ', "0").split(','))

matriz = np.zeros((len(matriz_letter),len(matriz_letter[-1])))

for i in range(len(matriz_letter)):
    for k in range(len(matriz_letter[i])):
        for number,letter in enumerate(crate2num):
            if matriz_letter[i][k].find(letter) != -1:
                matriz[i][k] = crate2num[letter]

print(matriz)

matriz_t = np.concatenate((np.zeros(matriz.shape),matriz))

[[ 0.  4.  0.]
 [14.  3.  0.]
 [26. 13. 16.]]


In [259]:
matriz_t

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [14.,  3.,  0.],
       [26., 13., 16.]])

In [245]:

for i in range(len(moves)):
    moving = moves[i][0]+3
    to = moves[i][2]-1
    col = moves[i][1]-1

    print(f"moving {moving-3} box from colum {col+1} to {to+1}")

    print(f'to {matriz_t[:,to][:moving]} from  {matriz_t[:,col][:moving]}')
    # print( matriz[:,to-1][:moving],matriz[:,col-1][:moving])
    matriz_t[:,to][:moving] = matriz_t[:,col][:moving]
    # print(matriz,matriz[:,col-1][-moving:])
    # matriz_t[:,col][:moving] = np.zeros(moving)
    # print(matriz)


moving 1 box from colum 2 to 1
to [0. 0. 0. 0.] from  [0. 0. 0. 4.]
moving 3 box from colum 1 to 3
to [ 0.  0.  0.  0.  0. 16.] from  [ 0.  0.  0.  4. 14. 26.]
moving 2 box from colum 2 to 1
to [ 0.  0.  0.  4. 14.] from  [0. 0. 0. 4. 3.]
moving 1 box from colum 1 to 2
to [0. 0. 0. 4.] from  [0. 0. 0. 4.]


In [248]:
for k in range(len(moves)):
    for i in range(matriz.shape[0]):
        for k in range(matriz.shape[0]):
            print(matriz[i][k])

0.0
4.0
0.0
14.0
3.0
0.0
26.0
13.0
16.0


In [262]:
matriz_t[:,2]

array([ 0.,  0.,  0.,  0.,  0., 16.])

In [280]:
tt = list(matriz[:,2])

In [281]:
tt.insert(2, 6)

In [282]:
tt

[0.0, 0.0, 6, 16.0]

In [287]:
teste = []
for i in matriz.T:
    teste.append(list(i))

In [288]:
teste

[[0.0, 14.0, 26.0], [4.0, 3.0, 13.0], [0.0, 0.0, 16.0]]

In [289]:
moves

[array([1, 2, 1]), array([3, 1, 3]), array([2, 2, 1]), array([1, 1, 2])]